### ISSUE TITLE
tf-big no matching distribution.

### ISSUE THREAD

**Issue by klize** [tf-encrypted/federated-aggregations#21]
I am using anaconda for my virtual enviroment.
- conda 4.8.5

I've created the virtual environment using python 3.7.9.

After cloning this source, running `pip install -r requirements.txt` shows this errors.
```bash
ERROR: Could not find a version that satisfies the requirement tf-big>=0.2.0 (from tf-encrypted-primitives~=0.1.1->-r requirements.txt (line 2)) (from versions: none)
ERROR: No matching distribution found for tf-big>=0.2.0 (from tf-encrypted-primitives~=0.1.1->-r requirements.txt (line 2))
```

To solve this, I've also got the source of `tf-big` since `pip install tf-big` still gives me the same error above, No matching distribution.

Here is the reproduction steps.
```bash
conda create -n fedagg python=3.7 -y
conda activate fedagg

git clone https://github.com/tf-encrypted/tf-big.git
cd tf-big
pip install -r requirements.txt
python setup.py install

cd ..

git clone https://github.com/tf-encrypted/federated-aggregations.git
cd federated-aggregations
pip install -r requirements.txt
python setup.py install

$ python examples/paillier.py
```

It comes with another error
```bash
...
tensorflow.python.framework.errors_impl.NotFoundError: xxx/anaconda3/envs/fedagg/lib/python3.7/site-packages/tf_big-0.2.1-py3.7-linux-x86_64.egg/tf_big/python/ops/_big_ops.so: cannot open shared object file: No such file or directory
```

What's wrong with it?  Much appreciated with your helps :)

**Comment by jvmncs** [comment]
Are you on an OS other than Mac OS? TF Big has only published a Mac OS wheel to PyPI for >=0.2.0 ([see here](https://pypi.org/project/tf-big/#files)), so pip will not be able to find a wheel on PyPI if you're on another system.

Building TF Big from source can be tricky, but it's out of scope for this repo. However it looks like you have not followed all of the [instructions for building that project from source](https://github.com/tf-encrypted/tf-big#development). If that doesn't work, please open a follow-up issue for that in the TF Big repository.
